### ISSUE TITLE
Switch to common ROM?

### ISSUE THREAD

**Issue by RetroGameTalk** [Krokodyl/treasure-conflix#1]
Hello, it seems like the source rom is proving hard to find.
The one i did find easily (nointro) wouldn't work:

 File: Treasure Conflix (Japan).bs
  CRC-32: f50fb0b7
     MD5: 534de4685ed6a099a31717826ad8ad8b
   SHA-1: dff1d22d662fed96f45ac3e722c79c93469ca421

Is there any chance you could use that for the patch?
Thanks!

**Comment by TheShadowRunner** [comment]
I agree a patch for the .BS rom would be cleaner!
https://datomatic.no-intro.org/index.php?page=show_record&s=77&n=3122

**Comment by Krokodyl** [comment]
Sure thing!
I separated the headered and headerless roms in different patches: 
[header](https://github.com/Krokodyl/treasure-conflix/tree/master/patch/header)
[headerless](https://github.com/Krokodyl/treasure-conflix/tree/master/patch/headerless)

Let me know if it works for you and I'll update the readme.

Personally, I prefer working with headerless roms. (It also happens that the first google result I get for "treasure conflix rom" is the headerless one I used but I'm aware that highly depends on your country)

**Comment by TheShadowRunner** [comment]
Thanks for the fast update. The thing is, only the .bs rom is considered clean (what you call "header") with crc F50FB0B7.
What you call "headerless" is a hack to bypass the BS menu and launch the game directly.
As for the rom with crc 5F374D96, no idea where you found it or what it's doing in the "header" readme.txt file, it's confusing. The BPS is supposed to check source rom crc and does apply to F50FB0B7 alright.

**Comment by Krokodyl** [comment]
> What you call "headerless" is a hack to bypass the BS menu and launch the game directly.

But it's really not. A binary comparison of the two roms shows that what you call a clean .bs rom is exactly the same with a SMC header (512 bytes). Both roms can be loaded from the BS menu and that's how I do it.
My understanding is that the SMC header was originally added by the Super Magicom Copier when dumping from cartridges. I wonder how it would be considered "cleaner" than the pure rom (especially since BS games where never meant to exist on a physical copie).

![image](https://user-images.githubusercontent.com/3762526/200203026-5d340fa6-48e3-46d5-a071-99abc7dbfa1b.png)

Thanks for the feedback!

**Comment by TheShadowRunner** [comment]
I'm actually saying the pure BS rom is the no-intro one with crc F50FB0B7 and .bs extension.
From the picture it seems you compared the other 2..

**Comment by Krokodyl** [comment]
I did compare with the F50FB0B7 rom (on the right)!
![image](https://user-images.githubusercontent.com/3762526/200212085-ef74515f-8b67-4af1-b0f1-7c0cfba7ecfe.png)

The CRC32 checksum shown in the Utility is the file checksum and it is different BECAUSE of the SMC header.
I'm willing to learn but I have yet to hear a compelling argument as to why the header is relevant for a BS game.

Would you have a link to the specification of the .bs file format?

**Comment by TheShadowRunner** [comment]
This ?
https://wiki.superfamicom.org/bs-x-satellaview-header

**Comment by Krokodyl** [comment]
This is the BS-X rom header, which is an extended version of the regular SNES rom header. Both of which have nothing to do with the SMC header as explained here:
https://en.wikibooks.org/wiki/Super_NES_Programming/SNES_memory_map#The_SNES_header
